### ISSUE TITLE
2021 lab gradescope

### ISSUE THREAD

**Issue by c8ef** [sunhuiquan/CMU-15-445-learn-note#1]
其实2021的gradescope也开放了 见下https://15445.courses.cs.cmu.edu/fall2021/faq.html

**Comment by sunhuiquan** [comment]
确实是，谢啦~

**Comment by sunhuiquan** [comment]
确实是hh，谢谢啦~



在 2021-11-04 23:03:09，"546" ***@***.***> 写道：

其实2021的gradescope也开放了 见下https://15445.courses.cs.cmu.edu/fall2021/faq.html

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
